FROM maven:3.8.2-jdk-11 as maven
RUN apt-get update
RUN apt-get install git -y
RUN mkdir /tmp/build
WORKDIR ~
RUN git clone https://github.com/dimur-devops/boxfuse_release.git
RUN mvn package -f boxfuse_release

FROM tomcat:latest
COPY --from=maven ~/boxfuse_release/target/hello-1.0.war /usr/local/tomcat/webapps/hello-1.0.war
