---
- name: get image boxfuse
  hosts: localhost
  become: yes

  tasks:
  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre-headless
  - name: download tomcat server packages
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
      dest: /usr/local
  - name: extract tomcat packages
    unarchive:
      src: /usr/local/apache-tomcat-9.0.54.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: Copy war to the Tomcat webapps
    copy:
      src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /usr/local/apache-tomcat-9.0.54/webapps
  - name: start tomcat services
    shell: nohup /usr/local/apache-tomcat-9.0.54/bin/startup.sh
