---
- name: published boxfuse app
  hosts: localhost
  become: yes

  tasks:
  - name: update repository
    apt:
      update_cache: yes
  - name: Ensure docker install
    apt:
      name: docker.io
      state: present
#  - name: Ensure python3-pip is install
#    apt:
#      name: python3-pip
#      state: present
#  - name: Ensure Docker SDK for Python is install
#    pip:
#      name: docker
#      state: present
#  - name: Ensure PyYAML is install
#    pip:
#      name: PyYAML
#      state: present
  - name: Ensure docker container is run
    docker_container:
      name: java_app
      image: dimamuro/boxfuse:1.0.2
      published_ports: 8081:8080
      state: started
